name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ftp.byting.at
          username: froeller-ftp
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /web/
